#! /bin/sh

# via) Mac の tmux でクリップボードを使う。 - こせきの技術日記
#        http://d.hatena.ne.jp/koseki2/20110816/TmuxCopy
tmux save-buffer /tmp/.tmux_to_pbcopy
cat /tmp/.tmux_to_pbcopy | pbcopy

# 以下はメッセージを表示するだけ。無くてもOK。
HEAD=`head -1 /tmp/.tmux_to_pbcopy`
TAIL=`tail -1 /tmp/.tmux_to_pbcopy`
tmux display-message "Copy:  $HEAD  -  $TAIL"
tmux deleteb
sleep 0.5

